spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peppa?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: caojiantao
    password: 123456

  redis:
    host: 140.143.132.236
    port: 6379