spring:
  datasource:
    url: jdbc:mysql://94.191.46.132:3306/husky?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: caojiantao
    password: cjt122208206202.
    hikari:
      idle-timeout: 600000

  redis:
    host: 127.0.0.1

  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 10Mb

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

qiniu:
  domain: http://po4leviy6.bkt.clouddn.com/
  access-key: 76ACZobjNtnou0OgwjlQv4ieJxZ8gXvlCPFSFHMW
  secret-key: 1uI-_dF0kKK_1UvPF1FjKSQoWFef3PTe_mX3SOZV
  bucket: husky

server:
  port: 8080
