spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peppa?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: caojiantao
    password: 123456

  redis:
    host: 140.143.132.236
    port: 6379

  http:
    encoding:
      force: true
      charset: UTF-8

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
