# 用户配置
project-env:
  datasource:
    host: 94.191.46.132
    port: 3306
    username: caojiantao
    password: Cjt201802136.
  redis:
    host: 127.0.0.1
    port: 6379

spring:
  datasource:
    url: jdbc:mysql://${project-env.datasource.host}:${project-env.datasource.port}/husky?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: ${project-env.datasource.username}
    password: ${project-env.datasource.password}
    hikari:
      idle-timeout: 600000

  redis:
    host: ${project-env.redis.host}
    port: ${project-env.redis.port}

  http:
    encoding:
      force: true
      charset: UTF-8

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

server:
  port: 8066
