spring:
  datasource:
    url: jdbc:mysql://94.191.46.132:3306/husky?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: caojiantao
    password: Cjt201802136.
    hikari:
      idle-timeout: 600000

  redis:
    host: 94.191.46.132

  http:
    encoding:
      force: true
      charset: UTF-8

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

server:
  port: 8080
