spring:
  datasource:
    url: jdbc:mysql://94.191.46.132:3306/husky?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: caojiantao
    password: cjt122208206202.
    hikari:
      idle-timeout: 600000

  redis:
    host: 127.0.0.1

  http:
    encoding:
      force: true
      charset: UTF-8

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

server:
  port: 8080
